### ISSUE TITLE
Image data augmentation

### ISSUE THREAD

**Issue by rodrigobarongavb** [GAVB-SERVICOS/Gumly#8]
Propose a module for image data augmentation.

Obs.: the most :+1: voted will be prioritized..

**Comment by Octavio-Santana** [comment]
We developed as accelerator for this purpose see [link](link https://github.com/GAVB-SERVICOS/gavb_acelerador_imageflow)
The data augmentation is applied to the image and bounding boxes, in case of object detection problems.

**Comment by rodrigobarongavb** [comment]
We will not introduce such feature in the lib!
